### ISSUE TITLE
Couldnt get any filings/documents/filers data in the db

### ISSUE THREAD

**Issue by samirsss** [piquette/edgr#2]
Hi,

I have setup the database correctly, since init does create the database tables and i see the forms metadata getting populated. 

 bin/edgr --pg-user postgres --pg-pass password --pg-db indexer --pg-addr localhost:5432 filers init --symbol AAPLinit
INFO[0000] connecting to postgres..
INFO[0000] connected
INFO[0000] retrieving single company
 100% |████████████████████████████████████████|  [0s:0s]INFO[0000] finished
INFO[0000] disconnected from postgres

Not sure what I am doing wrong here. I'd be ok to dig deeper and see whats going on but if its a quick issue would like some help.

**Comment by samirsss** [comment]
edgr --pg-user postgres --pg-pass password --pg-db indexer --pg-addr localhost:15432 filers init --all
INFO[0000] connecting to postgres..
INFO[0000] connected
INFO[0000] retrieving list of companies..
INFO[0000] gathering filer information, this will take a long time..
INFO[0003] disconnected from postgres
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/piquette/edgr/core.GetPublicCompanies()
	/Users/SSAVLA/git/edgr/core/core.go:68 +0x553
main.filersInitCommand(0xc0001c29a0)
	/Users/SSAVLA/git/edgr/cmd/filers.go:48 +0x185
github.com/urfave/cli.HandleAction({0x13e08e0, 0x14850c0}, 0x4)
	/Users/SSAVLA/git/StockAnalyzer/Common/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xa8
github.com/urfave/cli.Command.Run({{0x145f489, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x147cf66, 0x60}, {0x0, ...}, ...}, ...)
	/Users/SSAVLA/git/StockAnalyzer/Common/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x63a
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002b61c0, 0xc0001c26e0)
	/Users/SSAVLA/git/StockAnalyzer/Common/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:404 +0x9ec
github.com/urfave/cli.Command.startApp({{0x1460d1c, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x14795ce, 0x36}, {0x0, ...}, ...}, ...)
	/Users/SSAVLA/git/StockAnalyzer/Common/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:329 +0x6e9
github.com/urfave/cli.Command.Run({{0x1460d1c, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x14795ce, 0x36}, {0x0, ...}, ...}, ...)
	/Users/SSAVLA/git/StockAnalyzer/Common/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:102 +0x825
github.com/urfave/cli.(*App).Run(0xc0002b6000, {0xc000136000, 0xc, 0xc})
	/Users/SSAVLA/git/StockAnalyzer/Common/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0x80c
main.main()
	/Users/SSAVLA/git/edgr/cmd/main.go:60 +0xa19
